movie_server/movie_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('movie_ticketing.urls')),
    path('admin/', admin.site.urls),
]

movie_server/movie_ticketing/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home_view, name='home'),
    path('showings/<int:movie_id>/', views.showings_view, name='showings'),
    path('purchase/<int:showing_id>', views.purchase_view, name='purchase'),
]

movie_server/movie_ticketing/models.py
from django.db import models

# Create your models here.


class Movie(models.Model):
    title = models.CharField(max_length=250)
    image = models.URLField()
    runtime_hrs = models.IntegerField()
    runtime_mins = models.IntegerField()
    rating = models.CharField(max_length=250)


class Showing(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    ticket_price = models.DecimalField(decimal_places=2, max_digits=100)
    seats_available = models.IntegerField()
    seats_total = models.IntegerField()


class Ticket(models.Model):
    showing = models.ForeignKey(Showing, on_delete=models.CASCADE)
    ticket_code = models.CharField(max_length=50)
    ticket_type = models.CharField(max_length=50)
    ticket_used = models.BooleanField(default=False)
    buyer = models.EmailField()

movie_server/movie_ticketing/forms.py
from django import forms
from .models import Movie, Showing, Ticket


class TicketsForm(forms.Form):
    adult_tickets = forms.IntegerField(label="Adult Tickets (13 and up)")
    child_tickets = forms.IntegerField(label="Child Tickets (12 and under)")


class PurchaseForm(forms.Form):
    first_name = forms.CharField(label="First Name")
    last_name = forms.CharField(label="Last Name")
    email = forms.EmailField(label="Email")
    credit_card = forms.IntegerField(label="Credit Card")
    exp_month = forms.IntegerField(label="Expiration Month")
    exp_year = forms.IntegerField(label="Expiration Year")
    secret_code = forms.IntegerField(label="Secret Code")


# class ConfirmForm():
#     pass

# class TicketsForm(FlaskForm):
#     adult_tickets = IntegerField("Adult Tickets (13 and up)", validators=[DataRequired()])
#     child_tickets = IntegerField("Child Tickets (12 and under)", validators=[DataRequired()])
#     submit = SubmitField("Buy")
#
#
# class PurchaseForm(FlaskForm):
#     first_name = StringField("First Name", validators=[DataRequired()])
#     last_name = StringField("Last Name", validators=[DataRequired()])
#     email = StringField("Email", validators=[Email(), DataRequired()])
#     credit_card = IntegerField("Credit Card", validators=[DataRequired()])
#     exp_month = IntegerField("Expiration Month", validators=[DataRequired()])
#     exp_year = IntegerField("Expiration Year", validators=[DataRequired()])
#     secret_code = IntegerField("Secret Code", validators=[DataRequired()])
#     purchase_submit = SubmitField("Purchase")
#
# class ConfirmForm(FlaskForm):
#     confirm = SubmitField("Close")

movie_server/movie_ticketing/views.py
from django.shortcuts import render, redirect
from .models import Movie, Showing, Ticket
from .ticket_handler import TicketHandler
from .billing_handler import BillingHandler
from .forms import TicketsForm, PurchaseForm

# Create your views here.

# from flask import render_template, redirect, url_for
# from init import app, db
# from sqlalchemy import inspect
# from forms import TicketsForm, PurchaseForm,ConfirmForm

# Create Handler Objects

ticketer = TicketHandler()
biller = BillingHandler()
adult_tickets = 0
child_tickets = 0
total_tickets = 0
purchase_flag = 0


# ----------- Routes --------------


# Home

def home_view(request, *args, **kwargs):
    current_movies = Movie.objects.all()
    context = {
        'movies': current_movies
    }
    return render(request, "index.html", context)


def showings_view(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    context = {
        'movie': movie
    }
    return render(request, "showings.html", context)


def purchase_view(request, showing_id):
    global adult_tickets
    print(f"Adult Tickets: {adult_tickets}")
    global child_tickets
    print(f"Child Tickets: {child_tickets}")
    global total_tickets
    print(f"Total Tickets: {total_tickets}")
    global purchase_flag
    print(f"Purchase Flag: {purchase_flag}")
    showing = Showing.objects.get(id=showing_id)
    movie = Movie.objects.get(id=showing.movie.id)
    ticket_form = TicketsForm()
    purchase_form = PurchaseForm()
    # success_button = ConfirmForm()
    # fail_button = ConfirmForm()
    ticket_flag = False
    if total_tickets > showing.seats_available:
        ticket_flag = True
    if request.method == 'POST':
        ticket_form = TicketsForm(request.POST)
        purchase_form = PurchaseForm(request.POST)
        print(request.POST)
        print(request.POST.get("ticket_numbers"))
        print(f"ticket_form is valid: {ticket_form.is_valid()}")
        print(f"Ticket Errors: {ticket_form.errors}")
        print(f"purchase_form is valid: {purchase_form.is_valid()}")
        print(f"Purchase Errors: {purchase_form.errors}")
        if request.POST.get("ticket_numbers") == "ticket_numbers" and ticket_form.is_valid():
            print("Tickets Submitted")
            adult_tickets = ticket_form.cleaned_data['adult_tickets']
            child_tickets = ticket_form.cleaned_data['child_tickets']
            total_tickets = adult_tickets + child_tickets
            return redirect('purchase', showing_id)
        if request.POST.get("purchase_submit") == "purchase_tickets" and purchase_form.is_valid():
            print("Tickets Purchased")
            order = {
                'adult_tickets': adult_tickets,
                'child_tickets': child_tickets,
                'showing_id': showing_id,
                'total': adult_tickets * showing.ticket_price + child_tickets * showing.ticket_price / 2
            }
            print(order)
            billing_data = {
                'buyer': purchase_form.cleaned_data['email'],
                'first_name': purchase_form.cleaned_data['first_name'],
                'last_name': purchase_form.cleaned_data['last_name'],
                'cc_number': purchase_form.cleaned_data['credit_card'],
                'cc_month': purchase_form.cleaned_data['exp_month'],
                'cc_year': purchase_form.cleaned_data['exp_year'],
                'code': purchase_form.cleaned_data['secret_code']
            }
            print(billing_data)
            if biller.buy_tickets(purchases=order, billing_info=billing_data):
                new_seats = showing.seats_available - total_tickets
                showing.seats_available = new_seats
                showing.save()
                adult_tickets = 0
                child_tickets = 0
                total_tickets = 0
                purchase_flag = 1
                return redirect('purchase', showing_id)
            else:
                purchase_flag = 2
                return redirect('purchase', showing_id)
        if request.POST.get("success_submit") == "success_submit":
            purchase_flag = 0
            return redirect('home')
        if request.POST.get("fail_submit") == "fail_submit":
            purchase_flag = 0
            return redirect('purchase', showing_id)

    context = {
        'showing': showing,
        'movie': movie,
        'adult_price': showing.ticket_price,
        'child_price': showing.ticket_price / 2,
        'adult_tickets': adult_tickets,
        'child_tickets': child_tickets,
        'total_price': showing.ticket_price * adult_tickets + showing.ticket_price * child_tickets / 2,
        'ticket_form': ticket_form,
        'purchase_form': purchase_form,
        'ticket_flag': ticket_flag,
        'purchase_flag': purchase_flag
    }

    return render(request, "purchase.html", context)

movie_server/movie_ticketing/templates/footer.html
  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; Your Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

   <!-- Bootstrap core JavaScript -->
  {% load static %}
  <script src="{% static '/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static '/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Custom scripts for this template -->
  <script src="{% static '/js/clean-blog.min.js' %}"></script>

</body>

</html>

movie_server/movie_ticketing/templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Movie Time</title>

<!-- Bootstrap core CSS -->
  {% load static %}

  <link href="{% static '/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static '/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static '/css/clean-blog.min.css' %}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">Movie Time</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'home' %}">Home</a>
          </li>
          {% if not logged_in %}
          <li class="nav-item">
            <a class="nav-link" href="">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">Register</a>
          </li>
          {% endif %}
          {% if logged_in %}
          <li class="nav-item">
            <a class="nav-link" href="">Log Out</a>
          </li>
          {% endif %}
          <li class="nav-item">
            <a class="nav-link" href="">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

<!-- Page Header -->
  <header class="masthead" style="background-image: url('/static/img/banner.png')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>MOVIE TIME</h1>
            <span class="subheading">Go see a movie today!</span>
          </div>
        </div>
      </div>
    </div>
  </header>

movie_server/movie_ticketing/templates/index.html
{% include "header.html" %}


<div class="container">
    <div class="row">
    {% for movie in movies %}
        {% if movie.id > 0 %}
        <div class="col-3">
            <div class="card" style="width: 18rem;">
                <img src="{{movie.image}}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{movie.title}}</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">{{movie.runtime_hrs}} hrs {{movie.runtime_mins}} mins</li>
                        <li class="list-group-item">Rated {{movie.rating}}</li>
                    </ul>
                    <a href="{% url 'showings' movie.id %}" class="btn btn-primary">Buy Tickets!</a>
                </div>
            </div>
        </div>
        {% endif %}
    {% endfor %}
    </div>
</div>



{% include "footer.html" %}

movie_server/movie_ticketing/templates/purchase.html
{% include "header.html" %}

<div class="container">

    <h2>{{ movie.title }}</h2>
    <h3>{{ showing.date }} | {{ showing.time }} | Adult ${{ adult_price }} | Child ${{ child_price }}</h3>
    <hr>

</div>

<div class="container">
<form method="POST" action="">
    {% csrf_token %}
    {{ ticket_form.as_p }}
    <button name="ticket_numbers" type="submit" value="ticket_numbers">Submit</button>
</form>
</div>

<div class="modal" id="purchase-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Purchase Tickets</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><h5>{{ movie.title }}</h5></p>
          {% if child_tickets > 0 %}
            <p><h6>{{ adult_tickets }} adult tickets and {{ child_tickets }} child tickets for {{ showing.time }} showing on {{ showing.date }}.</h6></p>
          {% else %}
            <p><h6>{{ adult_tickets }} tickets for {{ showing.time }} showing on {{ showing.date }}.</h6></p>
          {% endif %}
          <p>Total Purchase: ${{ total_price }}</p>
          <hr>
        <form method="POST" action="">
                {% csrf_token %}
                {{ purchase_form.as_ul }}
                <button name="purchase_submit" type="submit" value="purchase_tickets">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="out-of-seats-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Not Enough Seats</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>You are attempting to purchase {{ tickets }} tickets.</p>
          <p>There are only {{ showing.seats_available }} seats left for this showing.</p>
          <p>Please purchase fewer tickets or choose a different showing.</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="payment-failed-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">PAYMENT FAILED</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p><h6>Something went wrong with your purchase!</h6></p>
          <p>Please review your payment details and try again.</p>
      </div>
      <div class="modal-footer">
        <form method="POST" action="">
            {% csrf_token %}
            <button name="fail_submit" type="submit" value="fail_submit">Confirm</button>
        </form>
      </div>
    </div>
  </div>
</div>

<div class="modal" id="payment-success-modal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Payment Success!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Your tickets will arrive in the provided email shortly.</p>
          <p>Thank you for using Movie Time!</p>
      </div>
      <div class="modal-footer">
        <form method="POST" action="">
            {% csrf_token %}
            <button name="success_submit" type="submit" value="success_submit">Confirm</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% include "footer.html" %}

{% block script %}
        {% if ticket_flag == True %}
            <script>
                var myModal = new bootstrap.Modal(document.getElementById('out-of-seats-modal'))
                myModal.show()
            </script>
        {% endif %}
        {% if purchase_flag == 2 %}
            <script>
                var myModal = new bootstrap.Modal(document.getElementById('payment-failed-modal'))
                myModal.show()
            </script>
        {% elif purchase_flag == 1 %}
            <script>
                var myModal = new bootstrap.Modal(document.getElementById('payment-success-modal'))
                myModal.show()
            </script>
        {% endif %}
        {% if adult_tickets|add:child_tickets > 0 and ticket_flag == False %}
            <script>
                var myModal = new bootstrap.Modal(document.getElementById('purchase-modal'))
                myModal.show()
            </script>
        {% endif %}
{% endblock %}

movie_server/movie_ticketing/templates/showings.html
{% include "header.html" %}

<div class="container">
<h2>{{ movie.title }}</h2>
<hr>
    <div class="container">
<ul>
    {% for showing in movie.showing_set.all %}
    <li>
        <div class="container">
        <a class="btn btn-primary" href="{% url 'purchase' showing.id %}">BUY</a>
        {{ showing.date }} | {{ showing.time }} | ${{ showing.ticket_price }}
        </div>
    </li>
    {% endfor %}
</ul>
</div>
</div>


{% include "footer.html" %}